### PR TITLE
Fix for the firing bug

### LINKED ISSUE #18: Fire Bug
There is an graphical issue in bullet firing, where if you keep the space button held for more than two consecutive frames, then a long continuous row of bullets will appear onscreen, which doesn't causes any damage to enemies...

To fix this, I will soon open a PR
fire_bug

### PR DESCRIPTION
**Pull request by HarshNarayanJha**
I have fixed the bug stated in issue #18 by just checking if the space key was held for long enough to stop firing that weird looking continuous bullets. 

Fixes #18

### CODE REVIEW

**Review by DiddiLeija — CHANGES_REQUESTED** [review]
Hmm... I just ran the CI, and seems like `black` (the code formatter I'm using) is unhappy. To fix this, open your fork locally, in an environment with Nox installed, then run `nox -s keep-codebase-clean`. Then push the changes here.

If you prefer that I do the changes, tell me!

**Comment by DiddiLeija** [comment]
I also edited your first post to link this PR with the issue, so we can close it after merging.

**Review by DiddiLeija — CHANGES_REQUESTED** [review]
I just tested locally. Indeed, the bug is now gone! :tada:

I can spot two things to make this PR ready:

1. Remove the `print`, at [line 165](https://github.com/DiddiLeija/diddi-and-the-bugs/pull/19/files#diff-b10564ab7d2c520cdd0243874879fb0a782862c3c902ab535faabe57d5a505e1R165)? On a Windows distribution, this won't be visible, but other distributions will fill up with unecessary information. You can still use `print` for testing purposes, but don't push them here.
2. Fix the code formatting, see https://github.com/DiddiLeija/diddi-and-the-bugs/pull/19#pullrequestreview-849329066.

**Comment by HarshNarayanJha** [comment]
> 1. Remove the `print`, at [line 165](https://github.com/DiddiLeija/diddi-and-the-bugs/pull/19/files#diff-b10564ab7d2c520cdd0243874879fb0a782862c3c902ab535faabe57d5a505e1R165)? On a Windows distribution, this won't be visible, but other distributions will fill up with unecessary information. You can still use `print` for testing purposes, but don't push them here.

Oh! Sorry, I forgot that one. Removed!

> 2\. Fix the code formatting, see [#19 (review)](https://github.com/DiddiLeija/diddi-and-the-bugs/pull/19#pullrequestreview-849329066).

I did it as you said, and here's the output:
image

But main.py wasn't changed. Is that OK?

**Comment by DiddiLeija** [comment]
Did you push the changes? On a Git local clone, run `git add .`, then run `git commit --message "{Commit message}"`, and finally `git push`.

**Comment by HarshNarayanJha** [comment]
I will push the changes after confirming this: https://github.com/DiddiLeija/diddi-and-the-bugs/issues/18#issuecomment-1011108919
Also, before committing and pushing, all that I wanted to know is that `nox` did nothing to `main.py` when I ran the command. Won't this will cause CI checks to fail here again?

**Comment by DiddiLeija** [comment]
> Also, before committing and pushing, all that I wanted to know is that `nox` did nothing to `main.py` when I ran the command. Won't this will cause CI checks to fail here again?

Hmm... It did, I don't know why. Did you run Nox in the same branch than the PR? Maybe that's the issue.

About the behavior changes, I will review them soon.

**Comment by HarshNarayanJha** [comment]
Ok! ran just `nox` command and it ran both tests, and this time it did reformat `main.py`, which was only rearrangement of some brackets on multiple lines.
image

Hopefully this time checks will pass!
Pushed the changes!

**Comment by HarshNarayanJha** [comment]
Hey! All checks passed @DiddiLeija!

**Review by DiddiLeija — APPROVED** [review]
Thanks @HarshNarayanJha! :tada:

**Pull request merged**
